// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/devices": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns the current connection and health status for all configured Modbus devices.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modbus"
                ],
                "summary": "List configured device status",
                "responses": {
                    "200": {
                        "description": "Device status list",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/modbusclient.DeviceStatusResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "Modbus service unavailable",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    }
                }
            }
        },
        "/devices/{device}/coils/{address}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Reads one or more coils from a configured Modbus device.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modbus"
                ],
                "summary": "FC 1: Read coils",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured device name",
                        "name": "device",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start address (decimal or 0x-prefixed hex)",
                        "name": "address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Number of values to read",
                        "name": "quantity",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Coils successfully read",
                        "schema": {
                            "$ref": "#/definitions/modbusclient.ReadBitsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Function code not allowed for the device",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Device not found",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Modbus read failed",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Bus queue full",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "504": {
                        "description": "Request waited too long in the bus queue",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Writes coils starting at the address. {\"value\": true} writes one coil with FC 5, {\"values\": [true, false]} writes one or more coils with FC 15 — also for a single value, for devices that only accept FC 15.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modbus"
                ],
                "summary": "FC 5 / FC 15: Write coils",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured device name",
                        "name": "device",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start address (decimal or 0x-prefixed hex)",
                        "name": "address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Either value (FC 5) or values (FC 15)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.ModbusWriteCoilsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Coils successfully written",
                        "schema": {
                            "$ref": "#/definitions/modbusclient.WriteResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Function code not allowed for the device",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Device not found",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Modbus write failed",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Bus queue full",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "504": {
                        "description": "Request waited too long in the bus queue",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    }
                }
            }
        },
        "/devices/{device}/discrete-inputs/{address}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Reads one or more discrete inputs from a configured Modbus device.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modbus"
                ],
                "summary": "FC 2: Read discrete inputs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured device name",
                        "name": "device",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start address (decimal or 0x-prefixed hex)",
                        "name": "address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Number of values to read",
                        "name": "quantity",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Discrete inputs successfully read",
                        "schema": {
                            "$ref": "#/definitions/modbusclient.ReadBitsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Function code not allowed for the device",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Device not found",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Modbus read failed",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Bus queue full",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "504": {
                        "description": "Request waited too long in the bus queue",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    }
                }
            }
        },
        "/devices/{device}/holding-registers/{address}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Reads one or more holding registers from a configured Modbus device.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modbus"
                ],
                "summary": "FC 3: Read holding registers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured device name",
                        "name": "device",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start address (decimal or 0x-prefixed hex)",
                        "name": "address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Number of values to read",
                        "name": "quantity",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Holding registers successfully read",
                        "schema": {
                            "$ref": "#/definitions/modbusclient.ReadRegistersResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Function code not allowed for the device",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Device not found",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Modbus read failed",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Bus queue full",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "504": {
                        "description": "Request waited too long in the bus queue",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Writes holding registers starting at the address. {\"value\": 7} writes one register with FC 6, {\"values\": [7, 8]} writes one or more registers with FC 16 — also for a single value, for devices that only accept FC 16.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modbus"
                ],
                "summary": "FC 6 / FC 16: Write holding registers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured device name",
                        "name": "device",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start address (decimal or 0x-prefixed hex)",
                        "name": "address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Either value (FC 6) or values (FC 16)",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/app.ModbusWriteRegistersRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Registers successfully written",
                        "schema": {
                            "$ref": "#/definitions/modbusclient.WriteResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Function code not allowed for the device",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Device not found",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Modbus write failed",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Bus queue full",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "504": {
                        "description": "Request waited too long in the bus queue",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    }
                }
            }
        },
        "/devices/{device}/input-registers/{address}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Reads one or more input registers from a configured Modbus device.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modbus"
                ],
                "summary": "FC 4: Read input registers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured device name",
                        "name": "device",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start address (decimal or 0x-prefixed hex)",
                        "name": "address",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Number of values to read",
                        "name": "quantity",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Input registers successfully read",
                        "schema": {
                            "$ref": "#/definitions/modbusclient.ReadRegistersResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Function code not allowed for the device",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Device not found",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Modbus read failed",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Bus queue full",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "504": {
                        "description": "Request waited too long in the bus queue",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    }
                }
            }
        },
        "/devices/{device}/status": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns the current connection and health status for one configured Modbus device.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "modbus"
                ],
                "summary": "Get device status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Configured device name",
                        "name": "device",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Device status",
                        "schema": {
                            "$ref": "#/definitions/modbusclient.DeviceStatusResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Device not found",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Modbus service unavailable",
                        "schema": {
                            "$ref": "#/definitions/app.ModbusErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieves memory usage, goroutine count, version, hostname, Go runtime version, and OS.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get health data",
                "responses": {
                    "200": {
                        "description": "Health data successfully retrieved",
                        "schema": {
                            "$ref": "#/definitions/health.Model"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Returns the current application name and version. No authentication required.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get application version and name",
                "responses": {
                    "200": {
                        "description": "Application version and name",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "app": {
                                    "type": "string"
                                },
                                "appVersion": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "app.ModbusErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "app.ModbusWriteCoilsRequest": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "boolean",
                    "example": true
                },
                "values": {
                    "type": "array",
                    "items": {
                        "type": "boolean"
                    }
                }
            }
        },
        "app.ModbusWriteRegistersRequest": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "integer",
                    "example": 7
                },
                "values": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "health.Model": {
            "type": "object",
            "properties": {
                "app": {
                    "description": "Application name (MODULE)",
                    "type": "string"
                },
                "appVersion": {
                    "description": "Current version of the application",
                    "type": "string"
                },
                "goVersion": {
                    "description": "Go runtime version",
                    "type": "string"
                },
                "heapAllocBytes": {
                    "description": "Allocated heap memory in bytes",
                    "type": "integer"
                },
                "hostname": {
                    "description": "Machine name where the app runs",
                    "type": "string"
                },
                "numGoroutines": {
                    "description": "Current number of active goroutines",
                    "type": "integer"
                },
                "os": {
                    "description": "Operating system name",
                    "type": "string"
                },
                "sysMemoryBytes": {
                    "description": "Total memory obtained from the OS",
                    "type": "integer"
                },
                "timestamp": {
                    "description": "UTC timestamp when health info was collected (RFC3339)",
                    "type": "string"
                },
                "uptimeSeconds": {
                    "description": "Application uptime in seconds",
                    "type": "number"
                }
            }
        },
        "modbusclient.DeviceStatusResponse": {
            "type": "object",
            "properties": {
                "bus": {
                    "type": "string"
                },
                "cacheHits": {
                    "type": "integer"
                },
                "cacheMisses": {
                    "type": "integer"
                },
                "connected": {
                    "description": "the bus connection is open",
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "device": {
                    "type": "string"
                },
                "functions": {
                    "description": "allowed function codes, e.g. [\"FC3\",\"FC4\"]",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "lastConnectAt": {
                    "type": "string"
                },
                "lastError": {
                    "type": "string"
                },
                "lastRequestAt": {
                    "type": "string"
                },
                "lastSuccessAt": {
                    "type": "string"
                },
                "queueLen": {
                    "description": "requests waiting on the bus",
                    "type": "integer"
                },
                "transport": {
                    "type": "string"
                },
                "unitId": {
                    "type": "integer"
                }
            }
        },
        "modbusclient.ReadBitsResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "integer"
                },
                "addressHex": {
                    "type": "string"
                },
                "cached": {
                    "description": "answered from the cache, without a bus transaction",
                    "type": "boolean"
                },
                "dataHex": {
                    "description": "packed, eight values per byte, first value in the lowest bit",
                    "type": "string"
                },
                "device": {
                    "type": "string"
                },
                "duration": {
                    "type": "number"
                },
                "functionCode": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "transport": {
                    "type": "string"
                },
                "unitId": {
                    "type": "integer"
                },
                "values": {
                    "description": "one value per address",
                    "type": "array",
                    "items": {
                        "type": "boolean"
                    }
                }
            }
        },
        "modbusclient.ReadRegistersResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "integer"
                },
                "addressHex": {
                    "type": "string"
                },
                "cached": {
                    "description": "answered from the cache, without a bus transaction",
                    "type": "boolean"
                },
                "dataHex": {
                    "description": "two bytes per register, big endian",
                    "type": "string"
                },
                "device": {
                    "type": "string"
                },
                "duration": {
                    "type": "number"
                },
                "functionCode": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "transport": {
                    "type": "string"
                },
                "unitId": {
                    "type": "integer"
                },
                "values": {
                    "description": "one unsigned value per register",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "modbusclient.WriteResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "integer"
                },
                "addressHex": {
                    "type": "string"
                },
                "dataHex": {
                    "type": "string"
                },
                "device": {
                    "type": "string"
                },
                "duration": {
                    "type": "number"
                },
                "functionCode": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                },
                "transport": {
                    "type": "string"
                },
                "unitId": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
